routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\doctoresController;
use App\Http\Controllers\{PacientesController,ConsultaController,AreasController,RecetaController,CitaController,RolController,PersonalizacionController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

// CONSULTA
Route::get('/showPatient',[ConsultaController::class, 'showPatient'])->name('consulta.showPatient');
Route::get('/consulta/createT/{id}',[ConsultaController::class, 'createT'])->name('consulta.createT');

// EMPLEADO
Route::get('/empleado/inactivar/{id}',[doctoresController::class, 'inactivar'])->name('empleado.inactivar');

// PACIENTE
Route::get('/paciente/inactivar/{id}',[PacientesController::class, 'inactivar'])->name('paciente.inactivar');
Route::get('paciente',[PacientesController::class, 'index'])->name('paciente.index');

// CONSULTA
Route::get('/consulta/inactivar/{id}',[ConsultaController::class, 'inactivar'])->name('consulta.inactivar');

// CITA
Route::get('/cita/inactivar/{id}',[CitaController::class, 'inactivar'])->name('cita.inactivar');

// RECETAS
Route::get('/receta/inactivar/{id}',[RecetaController::class, 'inactivar'])->name('receta.inactivar');
Route::get('/receta/verReceta/{id}',[RecetaController::class, 'verReceta'])->name('receta.verReceta');
Route::get('/returnIndex',[RecetaController::class, 'returnIndex'])->name('datatables.data');


// AREAS
Route::get('/area/inactivar/{id}',[AreasController::class, 'inactivar'])->name('area.inactivar');

//PERSONALIZACION
Route::get('/personalizacion/pantalla',[PersonalizacionController::class,'pantalla'])->name('personalizacion.pantalla');

Route::post('/personalizacion/store',[PersonalizacionController::class,'store'])->name('personalizacion.store');

Route::resources([
	'empleado' => doctoresController::class,
	'paciente' => PacientesController::class,
	'consulta' => ConsultaController::class,
	'area' => AreasController::class,
	'receta' => RecetaController::class,
	'cita' => CitaController::class,
	'rol' => RolController::class,
]);

Route::get('/soporte',[App\Http\Controllers\HomeController::class, 'soporte'])->name('soporte');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


//limpiar caches
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

resources/views/empleados/editEmpleado.blade.php
@extends('layouts.app')
@section('titulo','Editar Registro')

@section('content')
<style>
.error {
  color: #af5157;
}
</style>
<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.1.62/jquery.inputmask.bundle.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    var url = $('img').attr('src');
    console.log(url);
    $('.avatar').val(url);

    var phones = [{ "mask": "(###) ###-####"}];
    $('#phone').inputmask({ 
        mask: phones, 
        greedy: false, 
        definitions: { '#': { validator: "[0-9]", cardinality: 1}} });

    $("#formEmpleado").validate({
        rules: {
            first_name: {
                required: true
            },
            middle_name: {
                required: true
            },
            phone: {
                required: true
            },
            email: {
                required: true,
                email: true
            },
            birth_date: {
                required: true
            },
            gender: {
                required: true
            },
            street: {
                required: true
            },
            external_number: {
                required: true
            },
            neighborhood: {
                required: true
            },
            municipality: {
                required: true
            },
            city: {
                required: true
            },
            postal_code: {
                required: true,
                digits:true,
                minlength: 5,
                maxlength: 5
            },
            department_id: {
                required: true
            },
            rol_id: {
                required: true
            }
        },
        messages: {
            first_name: {
                required: "Nombre (s) requerido"
            },
            middle_name: {
                required: "Ap. Paterno requerido"
            },
            phone: {
				required: "Ap. Materno requerido"
            },
            email: {
                required: "Email requerido",
                email: "Formato: abc@domain.com"
            },
            birth_date: {
                required: "Fecha Nac. requerido"
            },
            gender: {
                required: "Genero requerido"
            },
            street: {
                required: "Calle requerido"
            },
            external_number: {
                required: "Num. Ext. requerido"
            },
            neighborhood: {
                required: "Colonia requerido"
            },
            municipality: {
                required: "Municipio requerido"
            },
            city: {
                required: "Ciudad requerido"
            },
            postal_code: {
                required: "C.P. requerido",
                digits: "Solo números",
                minlength: "5 Digitos",
                maxlength: "5 Digitos"
            },
            department_id: {
				required: "Departamento requerido"
            },
            rol_id: {
                required: "Rol requerido"
            }
        },
        submitHandler: function(form) {
           form.submit();
        }
    });
});
</script>

<div class="row">
    <div class="col-lg-8 offset-lg-1">
        <h4 class="page-title">Editar empleado</h4>
    </div>
</div>
<form method="post" id="formEmpleado" action="{{ route('empleado.update',$clave) }}" enctype="multipart/form-data">
    {{ method_field('put') }}
    @csrf

    @foreach($editEmploye as $key)
    <div class="row offset-lg-1">        
		<div class="form-group col-md-4">
            <label for="first_name">Nombre (s)</label>
            <input type="text" placeholder="Nombre (s)" value="{{$key->first_name}}" name="first_name" class="form-control ">
        </div>
		<div class="form-group col-md-3">
            <label for="middle_name">Apellido Paterno</label>
            <input type="text" value="{{$key->middle_name}}" placeholder="Apellido paterno" name="middle_name" class="form-control "
                value="{{old('nombreDos')}}">
        </div>
        <div class="form-group col-md-3">
            <label for="last_name">Apellido Materno</label>
            <input type="text" value="{{$key->last_name}}"  placeholder="Apellido materno" name="last_name" class="form-control ">
        </div>
               
    </div>

    <div class="row offset-lg-1">     
	<div class="form-group col-md-3">
            <label for="phone">Teléfono</label>
            <input type="text" value="{{$key->phone}}" placeholder="Telefono" id="phone" name="phone" class="form-control ">
        </div>
        <div class="form-group col-md-3">
            <label for="email">Email</label>
            <input type="email" value="{{$key->email}}" placeholder="Email" name="email" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="birth_date">Fecha de nacimiento</label>
            <input type="date" value="{{$key->birth_date}}" placeholder="Fecha de nacimiento" name="birth_date" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="gender">Genero</label>
            <select class="form-control" name="gender">
            <option value="">--Selecciona un genero--</option>
                <option value="Hombre" {{ ( $gender == 'Hombre' ) ? 'selected' : '' }} > Hombre </option>
                <option value="Mujer"{{ ( $gender == 'Mujer' ) ? 'selected' : '' }} > Mujer </option>
            </select>
        </div>
    </div>

    <div class="row  offset-lg-1"> 
		<div class="form-group col-md-10">
            <label for="street">Calle</label>
            <input type="text" placeholder="Calle" value="{{$key->street}}" name="street" class="form-control ">
        </div>       
	</div> 

	<div class="row  offset-lg-1"> 
	<div class="form-group col-md-2">
            <label for="external_number">N° Exterior</label>
            <input type="number" placeholder="Numero Ext" value="{{$key->external_number}}"  name="external_number" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="internal_number">N° Interior</label>
            <input type="number" placeholder="Numero Int" value="{{$key->internal_number}}" name="internal_number" class="form-control ">
        </div>

        <div class="form-group col-md-6">
            <label for="neighborhood">Colonia</label>
            <input type="text" placeholder="Colonia" value="{{$key->neighborhood}}" name="neighborhood" class="form-control ">
        </div>            
    </div>

    <div class="row offset-lg-1">
		<div class="form-group col-md-5">
            <label for="municipality">Municipio</label>
            <input type="text" placeholder="Municipio"  value="{{$key->municipality}}" name="municipality" class="form-control ">
        </div>
        <div class="form-group col-md-3">
            <label for="city">Ciudad</label>
            <input type="text" placeholder="Ciudad" value="{{$key->city}}" name="city" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="postal_code">Código Postal</label>
            <input type="text" placeholder="Código postal" value="{{$key->postal_code}}" name="postal_code" class="form-control ">
        </div>      
    </div>

    <div class="row offset-lg-1">
	<div class="form-group col-md-1">
            <label>Fotografia</label>
            <div class="profile-upload">
                <div class="upload-img">
                    <img alt="" id="imgAvatar" src="{{asset('storage/'.$key->avatar)}}" class="img-thumbnail">
                </div>
            </div>
        </div>
		
        <div class="form-group col-md-3">            
            <div class="form-group">
                <label for="exampleFormControlFile1">URL</label>
                <input type="file" class="form-control-file" name="avatar" id="avatar" value="{{$key->avatar}}">
            </div>            
        </div>

        <div class="form-group col-md-3">
            <label for="rol_id">Departamento</label>
            <select class="form-control" name="department_id">
                <option value="">-- Seleccione un departamento --</option>
                @foreach($departamentos as $key)
                <option value="{{$key->id}}" {{ ( $key->id == $department_id ) ? 'selected' : '' }} >{{$key->department}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group col-md-3">
            <label for="rol_id">Rol</label>
            <select class="form-control" name="rol_id">
                <option value="">-- Seleccione un rol --</option>
                @foreach($roles as $key)
                <option value="{{$key->id}}" {{ ( $key->id == $role_id ) ? 'selected' : '' }} >{{$key->rol}}</option>
                @endforeach
            </select>
        </div>
	</div>
	<div class="row offset-lg-1">
        <div class="col-md-10 form-group">
            <label>Biografia</label>
            <textarea class="form-control" name="biography" value="{{$key->biography}}"  rows="3"></textarea>
        </div>            
    </div>	

    <div class="row  offset-lg-8">
        <div class="col-md-3">
            <button type="submit" class="form-control btn btn-primary">Actualizar</button>
        </div>
    </div>
    @endforeach
</form>

<script type="text/javascript">
avatar.onchange = evt => {
    const [file] = avatar.files
    if (file) {
        imgAvatar.src = URL.createObjectURL(file)
        $("#imgAvatar").attr('height', '100px');
        $("#imgAvatar").attr('width', '100px');
    }
}
</script>
@endsection

resources/views/empleados/indexEmpleado.blade.php
@extends('layouts.app')
@section('titulo','Ver Contratados')

@section('content')
{{-- @if (Auth::user()->rol == 'Administrador') --}}

@include("errors.alert-danger")
@include("errors.alert-success")
@include("errors.alert-warning")
@include("errors.custom-alert")

<div class="row">
    <div class="col-lg-8 offset-lg-1">
        <h4 class="page-title">Empleados</h4>
    </div>
</div>
<div class="row offset-lg-1">
    <div class="col-md-12">
        <div class="col-md-3">
            <a href="{{url('empleado/create')}}" class="btn btn-primary">
                Nuevo Registro
            </a>
        </div>       
    </div>
</div>
</br>

{{-- LAS CARDS AQUI --}}
<div class="row offset-lg-1">
    @foreach($allEmployee as $valor)
    <div class="card" style="width: 12rem; height: 22rem; margin: 10px;">
        <img class="card-img-top" style="width: 12rem; height:12rem;" src="{{asset('storage/'.$valor->avatar)}}"
            alt="Card image cap">
        <div class="card-body">
            <p class="card-text">{{$valor->first_name." ".$valor->middle_name." ".$valor->last_name}}</p>            
            <a href="{{url('/empleado/'.encrypt($valor->id).'/edit')}}" class="btn btn-primary">Editar</a>

            <a href="#" class="btn btn-danger>
                <form action=" {{ route('empleado.inactivar',$valor->id) }}" method="DELETE" id="form_deleted_col">
                <input type="hidden" name="_method" value="DELETE">
                {{ csrf_field() }}
                <input type="hidden" name="id_eliminar" id="id_eliminar" value="{{$valor->id}}">
                <button class="btn btn-danger botonCus" type="submit"
                    onclick="return AlertEliminar(event,{{ $valor->id }})">
                    <input type="hidden" name="id_eliminar" id="id_eliminar" value="{{$valor->id}}">

                    <input class="btn btn-danger" style="width:50" type="image" src="img/eliminar.png" />
                </button>
                </form>
            </a>
        </div>
    </div>
    @endforeach
</div>

@endsection

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- <script src="{{url('js/jquery.dataTables.js')}}"></script> -->
<script type="text/javascript">
function AlertEliminar(event, id) {
    event.preventDefault();
    // var route = BASE_URL + "cuarto/borrar/" + id;
    var route = BASE_URL + "empleado/inactivar/" + id;
    // alert (route);
    swal({
        title: "¿Está seguro de eliminar este registro?",
        type: "warning",
        showCancelButton: true,
        confirmButtonClass: "btn-danger",
        confirmButtonText: "Si, Eliminalo!",
        closeOnConfirm: false
    }, function(inputValue) {
        if (inputValue === false) return false;

        // var form = $("#form_deleted_col").attr("action", route);
        // $("#form_deleted_col").submit();
        window.location = route;
        swal("Correcto!", "Se elimino correctamente", "success");
    });
}
</script>

resources/views/empleados/newEmpleado.blade.php
@extends('layouts.app')
@section('titulo','Nuevo Registro')

@section('content')
<style>
.error {
  color: #af5157;
}
</style>
<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.1.62/jquery.inputmask.bundle.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    var phones = [{ "mask": "(###) ###-####"}];
    $('#phone').inputmask({ 
        mask: phones, 
        greedy: false, 
        definitions: { '#': { validator: "[0-9]", cardinality: 1}} });

    $("#formEmpleado").validate({
        rules: {
            first_name: {
                required: true
            },
            middle_name: {
                required: true
            },
            phone: {
                required: true
            },
            email: {
                required: true,
                email: true
            },
            birth_date: {
                required: true
            },
            gender: {
                required: true
            },
            street: {
                required: true
            },
            external_number: {
                required: true
            },
            neighborhood: {
                required: true
            },
            municipality: {
                required: true
            },
            city: {
                required: true
            },
            postal_code: {
                required: true,
                digits:true,
                minlength: 5,
                maxlength: 5
            },
            department_id: {
                required: true
            },
            rol_name: {
                required: true
            }
        },
        messages: {
            first_name: {
                required: "Nombre (s) requerido"
            },
            middle_name: {
                required: "Ap. Paterno requerido"
            },
            phone: {
				required: "Ap. Materno requerido"
            },
            email: {
                required: "Email requerido",
                email: "Formato: abc@domain.com"
            },
            birth_date: {
                required: "Fecha Nac. requerido"
            },
            gender: {
                required: "Genero requerido"
            },
            street: {
                required: "Calle requerido"
            },
            external_number: {
                required: "Num. Ext. requerido"
            },
            neighborhood: {
                required: "Colonia requerido"
            },
            municipality: {
                required: "Municipio requerido"
            },
            city: {
                required: "Ciudad requerido"
            },
            postal_code: {
                required: "C.P. requerido",
                digits: "Solo números",
                minlength: "5 Digitos",
                maxlength: "5 Digitos"
            },
            department_id: {
				required: "Departamento requerido"
            },
            rol_name: {
                required: "Rol requerido"
            }
        },
        submitHandler: function(form) {
           form.submit();
        }
    });
});
</script>

<div class="row">
    <div class="col-lg-8 offset-lg-1">
        <h4 class="page-title">Nuevo empleado</h4>
    </div>
</div>
<form method="post" id="formEmpleado"  action="{{ route('empleado.store') }}" enctype="multipart/form-data">
    @csrf
    <div class="row offset-lg-1">
        <div class="form-group col-md-4">
            <label for="first_name">Nombre (s)</label>
            <input type="text" placeholder="Nombre (s)" name="first_name" class="form-control ">
        </div>
        <div class="form-group col-md-3">
            <label for="middle_name">Apellido Paterno</label>
            <input type="text" placeholder="Apellido paterno" name="middle_name" class="form-control "
                value="{{old('nombreDos')}}">
        </div>
        <div class="form-group col-md-3">
            <label for="last_name">Apellido Materno</label>
            <input type="text" placeholder="Apellido materno" name="last_name" class="form-control ">
        </div>
    </div>

    <div class="row offset-lg-1">
        <div class="form-group col-md-3">
            <label for="phone">Teléfono</label>
            <input type="text" placeholder="Telefono" id="phone" name="phone" class="form-control ">
        </div>
        <div class="form-group col-md-3">
            <label for="email">Email</label>
            <input type="email" placeholder="Email" name="email" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="birth_date">Fecha de nacimiento</label>
            <input type="date" placeholder="Fecha de nacimiento" name="birth_date" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="gender">Genero</label>
            <select class="form-control" name="gender">
            <option value="">--Selecciona un genero--</option>
                <option value="Hombre">Hombre</option>
                <option value="Mujer">Mujer</option>
            </select>
        </div>

    </div>

    <div class="row  offset-lg-1">
        <div class="form-group col-md-10">
            <label for="street">Calle</label>
            <input type="text" placeholder="Calle" name="street" class="form-control ">
        </div>
    </div>

    <div class="row  offset-lg-1">
        <div class="form-group col-md-2">
            <label for="external_number">N° Exterior</label>
            <input type="number" placeholder="Numero Ext" name="external_number" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="internal_number">N° Interior</label>
            <input type="number" placeholder="Numero Int" name="internal_number" class="form-control ">
        </div>

        <div class="form-group col-md-6">
            <label for="neighborhood">Colonia</label>
            <input type="text" placeholder="Colonia" name="neighborhood" class="form-control ">
        </div>
    </div>

    <div class="row  offset-lg-1">
        <div class="form-group col-md-5">
            <label for="municipality">Municipio</label>
            <input type="text" placeholder="Municipio" name="municipality" class="form-control ">
        </div>
        <div class="form-group col-md-3">
            <label for="city">Ciudad</label>
            <input type="text" placeholder="Ciudad" name="city" class="form-control ">
        </div>
        <div class="form-group col-md-2">
            <label for="postal_code">Código Postal</label>
            <input type="text" placeholder="Código postal" name="postal_code" class="form-control ">
        </div>
    </div>

    <div class="row offset-lg-1">        
        <div class="form-group col-md-1">
            <label>Fotografia</label>
            <div class="profile-upload">
                <div class="upload-img">
                    <img alt="" id="imgAvatar" src="{{url('img/usuario.png')}}" class="img-thumbnail">
                </div>
            </div>
        </div>
        <div class="form-group col-md-3">            
            <div class="form-group">
<<<<<<< HEAD
                <label for="exampleFormControlFile1">URL</label>
                <input type="file" class="form-control-file" name="avatar" id="avatar">
            </div>            
=======
                <div class="upload-input">
                    <input type="file" accept=".png, .jpg" class="form-control" name="avatar" id="avatar">
                </div>
            </div>
>>>>>>> 816366733e5361b04df15a3436e0da6340cd75a2
        </div>

        <div class="form-group col-md-3">
            <label for="department">Departamento</label>
            <select class="form-control" name="department_id">
                <option value="">-- Seleccione un departamento --</option>
                @foreach($departamentos as $k_department)
                <option value="{{$k_department->id}}">{{$k_department->department}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group col-md-3">
            <label for="rol">Rol</label>
            <select class="form-control" name="rol_name">
                <option value="">-- Seleccione un rol --</option>
                @foreach($roles as $k_rol)
                <option value="{{$k_rol->id}}">{{$k_rol->rol}}</option>
                @endforeach
            </select>
        </div>


    </div>
    <div class="row offset-lg-1">
        <div class="col-md-10 form-group">
            <label>Biografia</label>
            <textarea class="form-control" name="biography" rows="3"></textarea>
        </div>            
    </div>

    <div class="row  offset-lg-8" style="margin-top: 1%">
        <div class="col-md-3">
            <button type="submit" class="form-control btn btn-primary">Guardar</button>
        </div>
    </div>
    <br />
</form>

<script type="text/javascript">
avatar.onchange = evt => {
    const [file] = avatar.files
    if (file) {
        imgAvatar.src = URL.createObjectURL(file)
        $("#imgAvatar").attr('height', '100px');
        $("#imgAvatar").attr('width', '100px');
    }
}
</script>
@endsection